# Generated by Django 3.2.5 on 2021-07-25 14:11

import authentication.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, validators=[authentication.validators.ExcludeEmailValidator()], verbose_name='Email address'),
        ),
    ]
