# Generated by Django 3.2.5 on 2021-07-25 20:39

import authentication.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ipaddress',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Ip address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, validators=[authentication.validators.ExcludeEmailValidator(excludelist=['gmail.com', 'icloud.com'])], verbose_name='Email address'),
        ),
    ]
