# Generated by Django 3.2.5 on 2021-07-25 21:21

import authentication.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20210725_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, validators=[authentication.validators.ExcludeEmailValidator(excludelist=['gmail.com', 'icloud.com'])], verbose_name='Email address'),
        ),
    ]
