# Generated by Django 3.2.5 on 2021-07-27 19:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_auto_20210727_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9_]*$')], verbose_name='password'),
        ),
    ]
